name: rmc
title: rmc
url: https://randommeaninglesscharacters.com

#==================================================================================#
#                LINKS AND PATHS (for a slightly more modular site)                #
#==================================================================================#
#     internal links/paths
shopurl: https://shop.randommeaninglesscharacters.com

# https://cdn.randommeaninglesscharacters.com/guide/
imgdir: https://cdn.randommeaninglesscharacters.com/dsi-photos/
appdir: https://cdn.randommeaninglesscharacters.com/dsi-devapps/
releasedir: https://cdn.randommeaninglesscharacters.com/releases/
toolsdir: https://cdn.randommeaninglesscharacters.com/tools/
guidedir: https://cdn.randommeaninglesscharacters.com/guide/
blogdir: https://cdn.randommeaninglesscharacters.com/blog/
releasedir: https://cdn.randommeaninglesscharacters.com/releases/
imgui: https://cdn.randommeaninglesscharacters.com/ui-images/

#     external links
# appdir: https://archive.org/download/rmc-dsi_v2/
decrypt_tad: <a href="https://gist.github.com/rvtr/f1069530129b7a57967e3fc4b30866b4/">decrypt_tad.py</a>
twlipl: https://github.com/rvtr/TwlIPL/
twltoolsred: https://github.com/rvtr/TwlToolsRED/
# Note on github links:
#   - {{ site.twlipl }}/tree/<commithash>/path/to/file.txt
#   - {{ site.twlipl }}/tree/<branch>/path/to/file.txt

# This is for programs that are a part of a set (eg. TWL EVA IMPORT, TWL EVA AGING, TWL EVA MIC)
category-list: [TWL EVA, Nitro EVA, prototype firmware, TwlIPL test, bootloader/ntrboot]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from # Can we find something better? Redirects break when serving to another computer
feed:
  posts_limit: 20
